### ISSUE TITLE
commit msg를 잘못 작성하고 있음

### ISSUE THREAD

**Issue by level120** [devGW/PostApp#3]
@devGW 
대부분 Angular 컨벤션을 기반으로 하고 있기 때문에, 이 문서를 참고하면 좋을 것 같음.
https://www.conventionalcommits.org/ko/v1.0.0-beta.4/

간단하게 요약하자면 앞의 `type` 키워드는 아래만 사용이 가능함
(반드시는 아니지만 앵귤러 기반 개발자들의 약속으로 다른 분야에서도 사용 중).

```
[
  'build',
  'ci',
  'chore',
  'docs',
  'feat',
  'fix',
  'perf',
  'refactor',
  'revert',
  'style',
  'test'
]
```

그 중에서 자주 사용하는 키워드

```
[
  'chore',
  'docs',
  'feat',
  'fix',
  'perf',
  'refactor'
  'style',
  'test'
]
```

**Comment by zi-gae** [comment]
캄사합니다 👍
